services:
  - type: web
    name: mongoUse
    env: node
    buildCommand: "cd MongoUse && npm install"
    startCommand: "cd MongoUse && npm start"
    branch: master
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"  # You can set this if needed, but Render will usually auto-assign it

  # PR Previews
  - type: web
    name: mongoUse-pr-preview
    env: node
    buildCommand: "cd MongoUse && npm install"
    startCommand: "cd MongoUse && npm start"
    branch: pr
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"  # Similarly, you can optionally set this for PR previews
    pullRequestPreview: true
